services:
  sql:
    image: postgres:16
    restart: no
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=YourStrong!Passw0rd
      - POSTGRES_DB=movies
    ports:
      - "5432:5432"
    
    volumes:
      - sql:/var/opt/postgres


volumes:
  sql: