version: '3.9'
services:
    mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=YourStrong@Passw0rd
        - MSSQL_PID=Express
      ports:
        - "1433:1433"
      volumes:
        - mssql-data:/var/opt/mssql
      networks:
        - movies-network
      healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" -b -o /dev/null
        interval: 10s
        timeout: 5s
        retries: 5
    
    movieapi:
      build:
        context: ./Movies/Movies.Api
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
        - movies-network
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
#        - ConnectionStrings__MoviesDb=Server=mssql,1433;Database=MoviesDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      depends_on:
        - mssql
volumes:
  mssql-data:


networks:
  movies-network:
    driver: bridge